# golangci-lint configuration
run:
  timeout: 10m
  tests: false
  go: '1.21'
  skip-dirs:
    - vendor
    - third_party
    - testdata
    - examples
    - .git
    - build

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - ineffassign
    - misspell
  disable:
    - unused
    - gosec  # Too many false positives
    - revive  # Conflicts with other linters
    - gocritic  # Too strict for now
    - gofumpt  # Different from gofmt
    - unconvert  # Too many false positives
    - goimports  # Not needed with gofmt

linters-settings:
  govet:
    check-shadowing: false  # Too many false positives
  gofmt:
    simplify: true
  staticcheck:
    checks: ["all", "-SA1019"]  # Ignore deprecation warnings

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - staticcheck
        - ineffassign
    - path: test/
      linters:
        - staticcheck
        - ineffassign
    - path: cmd/
      text: "Error return value of .* is not checked"
    - text: "declaration of \"err\" shadows"
      linters:
        - govet
  max-issues-per-linter: 50
  max-same-issues: 10