run:
  timeout: 10m
  tests: false
  go: '1.21'

linters:
  enable:
    - gofmt
    - gofumpt
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - unconvert
    - gocritic
    - goimports
    - revive
    - gosec
  disable:
    - unused
    - deadcode
    - varcheck
    - exportloopref
    - depguard  # Disable depguard to allow internal imports

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/luxfi
  revive:
    rules:
      - name: unused-parameter
        disabled: true  # Disable unused parameter check for interface methods
  gocritic:
    enabled-checks:
      - nestingReduce
      - ruleguard
      - truncateCmp
    disabled-checks:
      - ifElseChain
      - hugeParam
      - unnamedResult
      - appendAssign
      - exitAfterDefer

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - gocritic
    
    # Exclude unused parameter warnings for interface implementations
    - text: "unused-parameter"
      linters:
        - revive
    
    # Exclude some specific checks in specific files
    - path: engine/
      text: "unused-parameter"
      linters:
        - revive
    
    - path: protocol/
      text: "unused-parameter"
      linters:
        - revive
    
    # Allow internal luxfi imports
    - path: \.go
      text: "import .* is not allowed"
      linters:
        - depguard
    
    # Exclude weak random in simulation tools
    - path: cmd/sim/
      linters:
        - gosec
    
    # Exclude integer overflow warnings for timestamps
    - path: protocol/quasar/
      text: "G115"
      linters:
        - gosec
    
    # Disable unconvert in engine code
    - path: engine/pq/
      linters:
        - unconvert
  
  max-issues-per-linter: 0
  max-same-issues: 0